import type { Metadata } from 'next'
import Link from 'next/link'

export const metadata: Metadata = {
  title: 'Terms of Service',
  description: 'DigiSurf Australia Terms of Service — the terms governing use of our website and services.',
}

export default function TermsOfService() {
  return (
    <main className="min-h-screen bg-[#050B18] pt-28 pb-20">
      <div className="max-w-3xl mx-auto px-6">
        <Link href="/" className="inline-flex items-center gap-2 text-sm text-[#7A8FA6] hover:text-[#00D4FF] transition-colors mb-10">
          ← Back to home
        </Link>

        <h1 className="text-3xl md:text-4xl font-bold text-white mb-3">Terms of Service</h1>
        <p className="text-sm text-[#7A8FA6] mb-10">Last updated: March 2026</p>

        <div className="prose prose-invert max-w-none space-y-8 text-[#7A8FA6] leading-relaxed">

          <section>
            <h2 className="text-xl font-semibold text-white mb-3">1. Agreement</h2>
            <p>By accessing <strong className="text-white">digisurfaustralia.com.au</strong> or engaging DigiSurf Australia Pty Ltd (ABN 28 448 210 292) for services, you agree to these Terms of Service. If you do not agree, please do not use this website or our services.</p>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-white mb-3">2. Services</h2>
            <p>DigiSurf Australia provides AI automation services including but not limited to AI receptionists, chatbots, voice agents, social media automation, document automation, and CRM integration. Specific deliverables, timelines, and pricing are agreed in writing before each engagement.</p>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-white mb-3">3. Subscriptions and Billing</h2>
            <ul className="list-disc list-inside space-y-1 mt-2">
              <li>All prices are in Australian Dollars (AUD) and include GST where applicable</li>
              <li>Monthly subscriptions are billed in advance</li>
              <li>Setup fees are charged once at the commencement of the engagement</li>
              <li>Cancellation requires 30 days written notice</li>
              <li>No refunds are provided for partial months</li>
            </ul>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-white mb-3">4. 30-Day ROI Guarantee</h2>
            <p>If your AI system does not demonstrate measurable time or cost savings within the first 30 days of going live, we will continue working on improvements at no additional cost until it does. This guarantee applies to systems that have been properly onboarded and integrated as agreed. It does not apply where the client has failed to provide necessary access, information, or cooperation.</p>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-white mb-3">5. Intellectual Property</h2>
            <p>Upon full payment, clients own the custom AI configurations, workflows, and integrations built for them. DigiSurf retains ownership of its underlying frameworks, templates, and proprietary methodologies. Content generated by AI systems belongs to the client.</p>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-white mb-3">6. Limitations of Liability</h2>
            <p>DigiSurf Australia&apos;s liability is limited to the amount paid in the preceding 3 months. We are not liable for indirect, incidental, or consequential losses. AI systems may occasionally produce errors — results should be reviewed before use in critical decisions.</p>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-white mb-3">7. Website Use</h2>
            <p>The content on this website is for general information only. DigiSurf Australia makes no warranties about accuracy or completeness. You may not use this website for unlawful purposes or in ways that infringe others&apos; rights.</p>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-white mb-3">8. Governing Law</h2>
            <p>These terms are governed by the laws of Queensland, Australia. Any disputes are subject to the exclusive jurisdiction of Queensland courts.</p>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-white mb-3">9. Contact</h2>
            <div className="mt-3 space-y-1">
              <p><strong className="text-white">Email:</strong> <a href="mailto:info@digisurfaustralia.com.au" className="text-[#00D4FF] hover:underline">info@digisurfaustralia.com.au</a></p>
              <p><strong className="text-white">Phone:</strong> <a href="tel:+61498541273" className="text-[#00D4FF] hover:underline">+61 498 541 273</a></p>
              <p><strong className="text-white">ABN:</strong> 28 448 210 292</p>
            </div>
          </section>

        </div>
      </div>
    </main>
  )
}
